services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
    environment:
      - 'ELASTIC_PASSWORD=secret'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200'
      - '9300'
    networks:
      - es-bridge

  kibana:
    container_name: kibana
    image: 'docker.elastic.co/kibana/kibana:7.17.10'
    environment:
      SERVER_NAME: 'kibana'
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
    ports:
      - '5601'
    depends_on:
      - elasticsearch
    networks:
      - es-bridge

networks:
  es-bridge:
    driver: bridge
