spring:
  docker:
    compose:
      file: spring-data-elasticsearch/compose.yaml

logging:
  level:
    org:
      springframework:
        core:
          LocalVariableTableParameterNameDiscoverer: error
